/*----------------------------------------------------------
MASV:20127451 - 20127492 - 20127626
HO TEN CAC THANH VIEN NHOM: Nguyen Nhat Canh - Lieu Gia Hao - To Duy Thai
LAB: 03 - NHOM 4
NGAY: 12/4/2023
----------------------------------------------------------*/

if db_id('QLSVNhom') is not null
	drop database QLSVNhom
GO

create database QLSVNhom
GO

use QLSVNhom
GO


CREATE TABLE SINHVIEN
(
	MASV NVARCHAR(20),
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(64) NOT NULL
	
	constraint PD_SV
	PRIMARY KEY (MASV)
)
GO

CREATE TABLE NHANVIEN
(
	MANV VARCHAR(20),
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(64),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(64) NOT NULL,
	PUBKEY VARCHAR(20)

	CONSTRAINT PK_NV
	PRIMARY KEY (MANV)
)
GO

CREATE TABLE LOP
(
	MALOP VARCHAR(20),
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20)

	CONSTRAINT PK_LOP
	PRIMARY KEY (MALOP)
)
GO

CREATE TABLE HOCPHAN
(
	MAHP VARCHAR(20),
	TENHP NVARCHAR(100) NOT NULL,
	SOTC INT

	CONSTRAINT PK_HP
	PRIMARY KEY (MAHP)
)
GO

CREATE TABLE BANGDIEM
(
	MASV VARCHAR(20),
	MAHP VARCHAR(20),
	DIEMTHI VARBINARY(64)

	CONSTRAINT PK_BD
	PRIMARY KEY (MASV, MAHP)
)
GO